### ISSUE TITLE
IndexError: list index out of range (doesn't like some postal codes)

### ISSUE THREAD

**Issue by timdau** [shmick/pcexpress-pickup#2]
# git show --oneline -s
0aa87be (HEAD -> master, origin/master, origin/HEAD) update readme

# python3 ./check_all_by_postal_code.py l8b0c1 1
Traceback (most recent call last):
  File "./check_all_by_postal_code.py", line 37, in <module>
    coords = geo_json[0]["geometry"]["coordinates"]
IndexError: list index out of range

**Comment by shmick** [comment]
It appears that `l8b0c1` doesn't return anything via the [NRC Geolocation Service](https://www.nrcan.gc.ca/earth-sciences/geography/topographic-information/web-services/geolocation-service/17304)

This returns empty https://geogratis.gc.ca/services/geolocation/en/locate?q=L8B"

If I go [here](https://www.postalcodesincanada.com/postal-code-l8b-0c1/) and look at the street names available and try a couple of address queries, they also return empty

https://geogratis.gc.ca/services/geolocation/en/locate?q=3+Blue+Jay+Court+Waterdown

https://geogratis.gc.ca/services/geolocation/en/locate?q=3+Blue+Jay+Court+Hamilton

My suggestion would be to try and use a nearby postal code that does work or use `city+province`

```
$ python ./check_all_by_postal_code.py waterdown+ontario 5 report
store: nofrills, location: 3114, address: 36 Clappison Ave Waterdown, Ontario L8B 0Y2
```

**Comment by shmick** [comment]
I've added a secondary lookup via `geocoder.ca` if the result from `geogratis.gc.ca` is empty

https://github.com/shmick/pcexpress-pickup/commit/45dba3f539c914ff7b6b2a17d22300b0650c8d70

**Comment by timdau** [comment]
Maybe make it so that you can select the lookup location?  This would resolve issue #3 also.

**Comment by shmick** [comment]
Closing this issue as it's resolved now
